# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
#
# GENERATED by tools/gen-python-declarations.mjs — do not hand-edit.
#
# Source: src/qualify-declarations.ts. The Python tools cannot import a TS module, so this file
# stands in for that import: regenerated and checked byte-identical instead of a second,
# hand-typed copy of the figures (2026-09-17 declare-derive audit, F8).
#
# Regenerate: node tools/gen-python-declarations.mjs --write
# Verify:     node tools/gen-python-declarations.mjs --check

COST_REFERENCE_RATE = 96000
QUANTUM_FRAMES = 1024
MEASURE_BASE_RATE = 48000
OPERATIONAL_RATE_FLOOR = 48000
QUALIFY_RATES = (44100, 48000, 96000, 192000)
QUALIFY_QUANTA = (128, 256, 512, 1024)
PLUGIN_TIMEOUT_S = 15
BOOT_TIMEOUT_S = 120
COST_TIMEOUT_S = 60
