// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
/**
 * The rates and quanta are declared once, in `src/qualify-declarations.ts`, and everything else
 * reads that declaration: a bare `96000`, `192000` or `1024` anywhere else in this package's
 * TypeScript, JavaScript or Python is a second copy that drifts the day the rate is changed.
 *
 * This is a text scan, so every negative is preceded by a positive control that proves the
 * pattern can see a real hit.
 *
 * Python is scanned too: `tools/benchmark.py` reads its rate and block size from the generated
 * `tools/_declarations.py` (`tools/gen-python-declarations.mjs`, checked byte-identical by
 * `python-declarations-conformance.test.ts`).
 */
import { cpSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const PKG = join(dirname(fileURLToPath(import.meta.url)), "..");

/** A bare 192000/96000 not part of a longer number. */
const RATE_LITERAL = /(?<![\d.])(?:96000|192000)(?![\d.])/;
/** A bare 1024 not part of a longer number. */
const QUANTUM_LITERAL = /(?<![\d.])1024(?![\d.])/;

/** The declaration itself, and the files this scan is not the right tool for, each with why. */
const ALLOWED: Record<string, string> = {
  "src/qualify-declarations.ts": "the one rate and quantum declaration: COST_REFERENCE_RATE, QUANTUM_FRAMES, QUALIFY_RATES",
  "tools/benchmark.py":
    "every rate, quantum and timeout imports from the generated tools/_declarations.py; the literals left are docstring worked examples (20e-9 * 96000) and the --rate usage example",
  "src/measurement/fixtures.ts": "round-trip document fixtures for the measurement-format tests: sample data, not a rate or quantum claim",
  "src/measurement/format.ts": "a docstring example of the per-rate key shape (\"96000\"), not a rate claim",
  "tools/lv2-measure.mjs": "a --rates usage example in help text, not a declaration",
  "tools/_declarations.py": "generated by tools/gen-python-declarations.mjs from src/qualify-declarations.ts and checked byte-identical",
};

const isScannedSource = (name: string): boolean => /\.(ts|mts|mjs|py)$/.test(name);
/** Tests assert against real rates by design: `.test.ts`, and Python's `test_*.py`. */
const isTest = (name: string): boolean => name.endsWith(".test.ts") || (name.startsWith("test_") && name.endsWith(".py"));

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (["dist", "node_modules", "fixtures", "__pycache__", ".git"].includes(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (isScannedSource(entry.name)) out.push(full);
  }
  return out;
}

const SCANNED = (root = PKG) => ["src", "tools", "bin"].flatMap((d) => walk(join(root, d)));

function scan(pattern: RegExp, root = PKG): { relPath: string; line: number; text: string }[] {
  const hits: { relPath: string; line: number; text: string }[] = [];
  for (const full of SCANNED(root)) {
    const rel = full.slice(root.length + 1);
    if (isTest(rel.slice(rel.lastIndexOf("/") + 1)) || ALLOWED[rel]) continue;
    readFileSync(full, "utf8").split("\n").forEach((line, i) => {
      if (pattern.test(line)) hits.push({ relPath: rel, line: i + 1, text: line.trim() });
    });
  }
  return hits;
}

describe("the rate and quantum are declared exactly once", () => {
  it("the scan sees the package's own source, Python included", () => {
    const files = SCANNED();
    expect(files.length).toBeGreaterThan(20);
    expect(files.some((f) => f.endsWith("qualify-declarations.ts"))).toBe(true);
    expect(files.some((f) => f.endsWith("benchmark.py"))).toBe(true);
  });

  it("a Python test file is walked but not scanned, as .test.ts is skipped", () => {
    expect(SCANNED().some((f) => f.endsWith("test_benchmark.py"))).toBe(true);
    expect(scan(RATE_LITERAL).filter((h) => h.relPath.endsWith("test_benchmark.py"))).toEqual([]);
  });

  it("sabotage: the patterns catch planted literals and pass unrelated numbers", () => {
    expect(RATE_LITERAL.test("const RATE = 192000;")).toBe(true);
    expect(RATE_LITERAL.test("const RATES = [44100, 48000, 96000, 192000];")).toBe(true);
    expect(RATE_LITERAL.test("const port = 8899;")).toBe(false);
    expect(QUANTUM_LITERAL.test("const QUANTUM = 1024;")).toBe(true);
    expect(QUANTUM_LITERAL.test("const MAX_BANDS = 640;")).toBe(false);
  });

  it("sabotage: a bare rate planted in a .py file on disk is caught", () => {
    // A copy of the scanned tree, so the planted file never sits in the real one.
    const root = mkdtempSync(join(tmpdir(), "plugin-qualify-scan-"));
    try {
      for (const d of ["src", "tools", "bin"]) cpSync(join(PKG, d), join(root, d), { recursive: true });
      writeFileSync(join(root, "tools", "__sabotage_probe.py"), "PLANTED_RATE = 96000\n");
      expect(scan(RATE_LITERAL, root).filter((h) => h.relPath.endsWith("__sabotage_probe.py")).length).toBe(1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("no bare rate literal outside the declaration and the named exclusions", () => {
    expect(scan(RATE_LITERAL)).toEqual([]);
  });

  it("no bare quantum literal outside the declaration and the named exclusions", () => {
    expect(scan(QUANTUM_LITERAL)).toEqual([]);
  });

  it("every excluded file still exists: an exclusion for a file that moved is a silent hole", () => {
    for (const rel of Object.keys(ALLOWED)) expect(() => readFileSync(join(PKG, rel), "utf8"), rel).not.toThrow();
  });
});
